name: TypeScript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: typescript

env:
  # enable debug logging
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install

    - name: Lint, Format, & Typecheck
      working-directory: typescript
      run: |
        bun run lint
        bun run format
        bun run typecheck

    - name: Build
      run: bun run build

    - name: Test
      run: bun run test
